# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4b07a8a24163293f6f5992da8ef5bfb95a276689ef3855a090ce39372da03cd0d9eafc764a676a44944974150e17edb914b7b8e961e01d0c7e503b21373638

test:
  secret_key_base: ec1f0aa08ae8ade9031877609c5c81f0559f63bbd81839191aab5f1bbb5084a694aa3b09a20b03870f887151c73f54ce66fbfe62808580dc301d1ea3789accfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
